app.version=1.0
app.id=com.dnd.anhbien
app.mainclass=com.dnd.anhbien.IOSLauncher
app.executable=LangLaNam
app.build=1
app.name=Làng Lá Nam
ios.signing.identity=Apple Distribution: Duy Nguyen Duc (7UG4U8PCU5)
ios.provisioning.profile=1e884c7d-fd59-478b-84e6-2f23cec216b9
